<?xml version="1.0" encoding="utf-8"?><Database Name="ProyectoFinalDB" Class="ConexionLinqSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HJH9G5O;Initial Catalog=ProyectoFinalDB;Persist Security Info=True;User ID=sa" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="ProyectoFinalDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.contratos_empleados" Member="contratos_empleados">
    <Type Name="contratos_empleados">
      <Column Name="id_contratos_empleados" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_contrato" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_contrato" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="sueldo_contrato" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="duracion_contrato_meses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado_contrato" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="rango_accesp_contrato " Member="rango_accesp_contrato" Type="System.Int32" DbType="int not null" CanBeNull="false" />
      <Association Name="contratos_empleados_detalle_contrato_empleado" Member="detalle_contrato_empleado" ThisKey="id_contratos_empleados" OtherKey="id_contratos_empleados" Type="detalle_contrato_empleado" />
    </Type>
  </Table>
  <Table Name="dbo.detalle_contrato_empleado" Member="detalle_contrato_empleado">
    <Type Name="detalle_contrato_empleado">
      <Column Name="id_detalle_contrato_empleados" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dpi_empleado" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="estado_contrato" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha_contrato" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tipo_empleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_contratos_empleados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="contratos_empleados_detalle_contrato_empleado" Member="contratos_empleados" ThisKey="id_contratos_empleados" OtherKey="id_contratos_empleados" Type="contratos_empleados" IsForeignKey="true" />
      <Association Name="empleados_detalle_contrato_empleado" Member="empleados" ThisKey="dpi_empleado" OtherKey="dpi_empleado" Type="empleados" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="clientes">
      <Column Name="dpi_cliente" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_cliente" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_cliente" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="direccion_cliente" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="telefono1_cliente" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="telefono2_cliente" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="email_cliente" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena_cliente" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="clientes_contrato_cliente_plan" Member="contrato_cliente_plan" ThisKey="dpi_cliente" OtherKey="dpi_cliente" Type="contrato_cliente_plan" />
    </Type>
  </Table>
  <Table Name="dbo.empleados" Member="empleados">
    <Type Name="empleados">
      <Column Name="dpi_empleado" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_empleado" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellidos_empleado" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telefono_empleado" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="email_empleado" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="usuario_empleado" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena_empleado" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="direccion_empleado" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="estado_empleado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="empleados_detalle_contrato_empleado" Member="detalle_contrato_empleado" ThisKey="dpi_empleado" OtherKey="dpi_empleado" Type="detalle_contrato_empleado" />
      <Association Name="empleados_relacion_mision_empleado" Member="relacion_mision_empleado" ThisKey="dpi_empleado" OtherKey="dpi_empleado" Type="relacion_mision_empleado" />
      <Association Name="empleados_Historial" Member="Historial" ThisKey="dpi_empleado" OtherKey="dpi_empleado" Type="Historial" />
    </Type>
  </Table>
  <Table Name="dbo.departamento" Member="departamento">
    <Type Name="departamento">
      <Column Name="id_depto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_depto" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="departamento_municipio" Member="municipio" ThisKey="id_depto" OtherKey="id_depto" Type="municipio" />
    </Type>
  </Table>
  <Table Name="dbo.municipio" Member="municipio">
    <Type Name="municipio">
      <Column Name="id_muni" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_muni" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="id_depto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="municipio_zonas" Member="zonas" ThisKey="id_muni" OtherKey="id_muni" Type="zonas" />
      <Association Name="departamento_municipio" Member="departamento" ThisKey="id_depto" OtherKey="id_depto" Type="departamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.servicio" Member="servicio">
    <Type Name="servicio">
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_servicio" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="estado_servicio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_servicio" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Association Name="servicio_disponibilidades" Member="disponibilidades" ThisKey="id_servicio" OtherKey="id_servicio" Type="disponibilidades" />
      <Association Name="servicio_detalle_plan" Member="detalle_plan" ThisKey="id_servicio" OtherKey="id_servicio" Type="detalle_plan" />
    </Type>
  </Table>
  <Table Name="dbo.disponibilidades" Member="disponibilidades">
    <Type Name="disponibilidades">
      <Column Name="id_disponibilidades" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado_disponibilidad" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="servicio_disponibilidades" Member="servicio" ThisKey="id_servicio" OtherKey="id_servicio" Type="servicio" IsForeignKey="true" />
      <Association Name="zonas_disponibilidades" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zonas" Member="zonas">
    <Type Name="zonas">
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_zona" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="id_muni" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="zonas_disponibilidades" Member="disponibilidades" ThisKey="id_zona" OtherKey="id_zona" Type="disponibilidades" />
      <Association Name="zonas_contrato_cliente_plan" Member="contrato_cliente_plan" ThisKey="id_zona" OtherKey="id_zona" Type="contrato_cliente_plan" />
      <Association Name="municipio_zonas" Member="municipio" ThisKey="id_muni" OtherKey="id_muni" Type="municipio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.planes" Member="planes">
    <Type Name="planes">
      <Column Name="id_plan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_plan" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_plan" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="precio_plan" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="precio_instalacion" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="minimo_meses_contratacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado_plan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="planes_contrato_cliente_plan" Member="contrato_cliente_plan" ThisKey="id_plan" OtherKey="id_plan" Type="contrato_cliente_plan" />
      <Association Name="planes_detalle_plan" Member="detalle_plan" ThisKey="id_plan" OtherKey="id_plan" Type="detalle_plan" />
    </Type>
  </Table>
  <Table Name="dbo.contrato_cliente_plan" Member="contrato_cliente_plan">
    <Type Name="contrato_cliente_plan">
      <Column Name="id_contrato_cliente_plan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dpi_cliente" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="id_plan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_contratacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="direccion_de_cobro" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="direccion_contrato" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="estado_contrato" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="nit_facturacion" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="id_zona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="detalles_contrato" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="precio_plan" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Association Name="contrato_cliente_plan_solicitudes_de_contrato" Member="solicitudes_de_contrato" ThisKey="id_contrato_cliente_plan" OtherKey="id_contrato_cliente_plan" Type="solicitudes_de_contrato" />
      <Association Name="contrato_cliente_plan_encabezado_facturas" Member="encabezado_facturas" ThisKey="id_contrato_cliente_plan" OtherKey="id_contrato_cliente_plan" Type="encabezado_facturas" />
      <Association Name="planes_contrato_cliente_plan" Member="planes" ThisKey="id_plan" OtherKey="id_plan" Type="planes" IsForeignKey="true" />
      <Association Name="clientes_contrato_cliente_plan" Member="clientes" ThisKey="dpi_cliente" OtherKey="dpi_cliente" Type="clientes" IsForeignKey="true" />
      <Association Name="zonas_contrato_cliente_plan" Member="zonas" ThisKey="id_zona" OtherKey="id_zona" Type="zonas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.detalle_plan" Member="detalle_plan">
    <Type Name="detalle_plan">
      <Column Name="id_detalle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_plan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado_detalle" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="servicio_detalle_plan" Member="servicio" ThisKey="id_servicio" OtherKey="id_servicio" Type="servicio" IsForeignKey="true" />
      <Association Name="planes_detalle_plan" Member="planes" ThisKey="id_plan" OtherKey="id_plan" Type="planes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cuota" Member="cuota">
    <Type Name="cuota">
      <Column Name="id_cuota" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_cuota" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_cuota" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="costo_cuota" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="estado_cuota" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="cuota_solicitudes_de_contrato" Member="solicitudes_de_contrato" ThisKey="id_cuota" OtherKey="id_cuota" Type="solicitudes_de_contrato" />
    </Type>
  </Table>
  <Table Name="dbo.solicitudes_de_contrato" Member="solicitudes_de_contrato">
    <Type Name="solicitudes_de_contrato">
      <Column Name="id_solicitudes_de_contrato" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_solicitud" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_contrato_cliente_plan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_pago" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="estado_solicitud" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha_completacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_cuota" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="concepto_solicitud" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Association Name="solicitudes_de_contrato_encabezado_misiones" Member="encabezado_misiones" ThisKey="id_solicitudes_de_contrato" OtherKey="id_solicitudes_de_contrato" Type="encabezado_misiones" />
      <Association Name="contrato_cliente_plan_solicitudes_de_contrato" Member="contrato_cliente_plan" ThisKey="id_contrato_cliente_plan" OtherKey="id_contrato_cliente_plan" Type="contrato_cliente_plan" IsForeignKey="true" />
      <Association Name="cuota_solicitudes_de_contrato" Member="cuota" ThisKey="id_cuota" OtherKey="id_cuota" Type="cuota" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.encabezado_misiones" Member="encabezado_misiones">
    <Type Name="encabezado_misiones">
      <Column Name="id_misiones" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_creacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="concepto_mision" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_programada" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estado_mision" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_solicitudes_de_contrato" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado_asignacion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="encabezado_misiones_relacion_mision_empleado" Member="relacion_mision_empleado" ThisKey="id_misiones" OtherKey="id_misiones" Type="relacion_mision_empleado" />
      <Association Name="solicitudes_de_contrato_encabezado_misiones" Member="solicitudes_de_contrato" ThisKey="id_solicitudes_de_contrato" OtherKey="id_solicitudes_de_contrato" Type="solicitudes_de_contrato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.relacion_mision_empleado" Member="relacion_mision_empleado">
    <Type Name="relacion_mision_empleado">
      <Column Name="id_relacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dpi_empleado" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="id_misiones" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="empleados_relacion_mision_empleado" Member="empleados" ThisKey="dpi_empleado" OtherKey="dpi_empleado" Type="empleados" IsForeignKey="true" />
      <Association Name="encabezado_misiones_relacion_mision_empleado" Member="encabezado_misiones" ThisKey="id_misiones" OtherKey="id_misiones" Type="encabezado_misiones" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.encabezado_facturas" Member="encabezado_facturas">
    <Type Name="encabezado_facturas">
      <Column Name="id_factura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_creacion_factura" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="monto_factura" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="mora_factura" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="total_factura" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="estado_factura" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha_pago_factura" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_contrato_cliente_plan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dias_retraso_pago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ultima_fecha_mora" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="contrato_cliente_plan_encabezado_facturas" Member="contrato_cliente_plan" ThisKey="id_contrato_cliente_plan" OtherKey="id_contrato_cliente_plan" Type="contrato_cliente_plan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Historial" Member="Historial">
    <Type Name="Historial">
      <Column Name="id_historial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dpi_empleado" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="concepto" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_realizado" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="empleados_Historial" Member="empleados" ThisKey="dpi_empleado" OtherKey="dpi_empleado" Type="empleados" IsForeignKey="true" />
    </Type>
  </Table>
</Database>